apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $NAMESPACE-$ROLE-$USERNAME-rolebinding
  namespace: $NAMESPACE
subjects:
  # You can specify more than one "subject"
  - kind: User
    name: $USERNAME # "name" is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # Role or ClusterRole
  name: $ROLE-role # name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
